#!/bin/bash

echo "Deleted files currently in trash:"
while read -r line; do
	filename="${line%/*}"
	unixtime=$(echo $line | awk -F"~" ' { print $NF }')
	date=$(date -d @$unixtime +%D\ %r)
	echo "$filename ($date)"
done < ~/.trash/trashregister
