#!/bin/bash

# How to save what you just killed? Use unrm! :)
# Written by Jack Conger, 2014

# ARGUMENT HANDLING

if [[ $# -eq 0 ]]; then
	echo "unrm: missing operand."
	echo "try 'unrm --help' for more information."
	exit 1
elif [[ $1 = "--help" ]]; then
	echo "Usage: unrm FILE..."
	echo "Unrm: To bring back things which have been sent to the trash by rmpp."
	echo "option --last: To bring back the latest removed thing."
	echo ""
	echo "Created by Jack Conger 2014."
	exit 0
fi

wdir=$(pwd)

if [[ $1 = "--last" ]]; then
	lastline=$(tail -1 ~/.trash/trashregister)
	lasttime=${lastline##*~}
	
	while read -r line; do
		if ! [[ $line =~ $lasttime ]]; then
			continue
		fi
		tounrm=$(echo "$line" | cut -f 1)
		unrm $tounrm
	done < ~/.trash/trashregister

	exit 0
fi

# THE MEAT

defIFS=$IFS
IFS='
'

for ftounrm in "$@"; do
	IFS=$defIFS
	cd $(dirname -- "$ftounrm")
	fullpath=$(pwd)
	justfname="${ftounrm##*/}"
	if [[ -z $justfname ]]; then
		justfname=${ftounrm%?##*/}
		justfname=${justfname%?}
	fi

	justfname=$(echo "$justfname" | sed -r "s/\*/\.\*/g")

	filefound=""

	while read -r line; do
		target=${line%/*}
		fnameintrash=${line##*/}
		if [[ -n $fnameintrash ]]; then
			filefound=1
			IFS='
'
			if [[ -e $target ]]; then
				dups=1
				while true; do
					if [[ -e ${target%/*}/$dups.${target##*/} ]]; then
						let dups=dups+1
					else
						break
					fi
				done
				target=${target%/*}/$dups.${target##*/}
			fi

			mv -f ~/.trash/$fnameintrash $target
			
			IFS=$defIFS
		fi
	done < <(grep "^$fullpath/$justfname\>" ~/.trash/trashregister)
	if [[ -z $filefound ]]; then
		echo "File not found in trash."
		cd $wdir
		exit 1
	fi
	grep -v "^$fullpath/$justfname\>" ~/.trash/trashregister > ~/.trash/newtrashreg
	mv -f ~/.trash/newtrashreg ~/.trash/trashregister
done

cd $wdir
IFS=$defIFS
